version: 2.1
orbs:
  azure-aks: circleci/azure-aks@0.2.1
jobs:
  dev-deploy:
    executor: azure-aks/azure-docker
    steps:
      - checkout
      - run:
          command: az login -u ${USER} -p ${PASS}
          name: Sign In to Azure CLI
      - azure-aks/update-kubeconfig-with-credentials:
          cluster-name: C1
          install-kubectl: true
          resource-group: G1
      - run:
          command: kubectl apply -f app1.yaml --namespace ingress-basic
          name: Apply new deployment app 1
      - run:
          command: kubectl apply -f app2.yaml --namespace ingress-basic
          name: Apply new deployment app 2
  approval-job:
  prod-deploy:
    executor: azure-aks/azure-docker
    steps:
      - checkout
      - run:
          command: az login -u ${USER} -p ${PASS}
          name: Sign In to Azure CLI
      - azure-aks/update-kubeconfig-with-credentials:
          cluster-name: production
          install-kubectl: true
          resource-group: Produc
      - run:
          command: kubectl apply -f app1.yaml --namespace ingress-basic
          name: Apply new deployment app 2
      - run:
          command: kubectl apply -f app2.yaml --namespace ingress-basic
          name: Apply new deployment app 1
workflows:
  build-and-test:
    jobs:
      - dev-deploy:
          filters:
              branches:
                  only: master
      - approval-job:
          type: approval
          requires:
              - dev-deploy
          filters:
            branches:
                only: master
      - prod-deploy:
          filters:
              branches:
                  only: master
          requires:
              - approval-job